config/routes.rb
Sephora::Application.routes.draw do

  #mobile
  scope path: :mobile, as: "m" do
    match "/", :to => 'mobile#home', :as => 'home'
    match "download", :to => "mobile#download", :as => "download"
    match 'politicas-de-privacidad', :to => 'mobile#politicas', :as => 'politicas'
    match 'politicas-de-devoluciones', :to => 'mobile#devoluciones', :as => 'politicas_devoluciones'
    match 'rebajas', :to => 'mobile/categorias#rebajas', :as => 'promociones_show'
    match 'obsequios', :to => 'mobile/categorias#obsequios', :as => 'obsequios'

    #carrousels
    match 'carrusel/:slug', to: "mobile/carrusel#show"
    match 'landing/:slug', to: "mobile/landings#show"

    match 'favorites(/:id)', :to => 'secciones#favorites', :as => 'favorites'

    #favoritoslabios
    match "/favoritoslabios", :to => 'mobile#favoritoslabios', :as => 'favoritoslabios'

    # favoritosmascarillas
    match "/favoritosmascarillas", :to => 'mobile#favoritosmascarillas', :as => 'favoritosmascarillas'

    # mascarillas
    get 'facemask', :to => 'mobile/secciones#mascarillasantiedad', as: :mascarillasantiedad
    get 'eyemask', :to => 'mobile/secciones#mascarillasmultibeneficio', as: :mascarillasmultibeneficio
    get 'sleepingmask', :to => 'mobile/secciones#mascarillashidratantes', as: :mascarillashidratantes

    get 'mascarillasingredientesnaturales', to: 'mobile/secciones#mascarillasingredientesnaturales', as: :mascarillasingredientesnaturales
    get 'beneficiosmascarillas', to: 'mobile/secciones#beneficiosmascarillas', as: :beneficiosmascarillas

    #marcas
    match "/marcas", :to => 'mobile/marcas#index', :as => 'marcas'
    resources :marca, controller: 'mobile/marcas', :except => [:index]
    scope path: :marca, :as => "marca" do
    end

    #popups
    resources :popups do
      collection do
        match 'subscribe', to: 'popups#subscribe', via: [:get, :post], as: :subscribe
        match 'campaing/:popup', to: 'popups#campaing', via: [:get], as: :campaing
      end
    end

    #Landings
    match "/fenty-beauty", to: "mobile/landings#fenty", via:[:get], as: "fenty"
    match "/beautyclasses", to: "mobile/landings#beautyclasses", via:[:get], as: "beautyclasses"
    match "/beautyfair", to: "mobile/landings#beautyfair", via: [:get, :post], as: "beautyfair"
    match "/masterclass", to: "mobile/landings#masterclass", via: [:get, :post], as: "masterclass"
    match "/veracruz", to: "mobile/landings#veracruz", via: [:get, :post], as: "veracruz"
    match "/opening", to: "mobile/landings#opening", via: [:get, :post], as: "opening"
    match '/oasis', :to => 'mobile/landings#oasis', via: [:get, :post], as: "oasis"
    match '/monterrey', :to => 'mobile/landings#monterrey', via: [:get, :post], as: "monterrey"
    match '/brow-collection', :to => 'mobile/landings#brow_collection', via: [:get, :post], as: "brow_collection"
    match '/bellezaparallevar', :to => 'mobile/landings#bellezaparallevar', via: [:get, :post], as: "bellezaparallevar"
    match '/promocionessephora', :to => 'mobile/landings#promocionessephora', via: [:get, :post], as: "promocionessephora"
    match '/regala-con-amor', :to => 'mobile/landings#regalaconamor', via: [:get, :post], as: "regalaconamor"
    match '/smashboxcovershotpalette', :to => 'mobile/landings#smashboxcovershotpalette', via: [:get, :post], as: "smashboxcovershotpalette"
    match '/cliniquecrayola', :to => 'mobile/landings#crayola', via: [:get, :post], as: "crayola"
    match '/promociondiadelasmadres', :to => 'mobile/landings#promociondiadelasmadres', via: [:get, :post], as: "promociondiadelasmadres"

    match "/lista_eventos", :to => 'mobile/eventos#index', :as => 'eventos'
    match "/eventos", :to => 'mobile/eventos#index', :as => 'eventos'
    resources :evento, controller: 'mobile/eventos', :except => [:index]
    scope path: :evento, :as => "evento" do
    end

    match "/tiendas", :to => 'mobile/tiendas#index', :as => 'tiendas'
    resources :tienda, controller: 'mobile/tiendas', :except => [:index]
    scope path: :tienda, :as => "tienda" do
    end

    match "/minimakeovers", :to => 'mobile/minimakeovers#index', :as => 'minimakeovers'
    match "/makeoverpersonalizado", :to => 'mobile/minimakeovers#index', :as => 'makeoverpersonalizado'
    match "/beautyunoauno", :to => 'mobile/minimakeovers#index', :as => 'beautyunoauno'
    match "/consultapersonalizadabelleza", :to => 'mobile/minimakeovers#index', :as => 'consultapersonalizadabelleza'
    resources :minimakeover, controller: 'mobile/minimakeovers', :except => [:index]
    scope path: :minimakeover, :as => "minimakeover" do
    end

    match "/posts", :to => 'mobile/posts#index', :as => 'posts'
    match "/posts/:id", :to => 'mobile/posts#show', :as => 'posts_show'
    resources :post, controller: 'mobile/posts', :except => [:index]
    scope path: :post, :as => "post" do
    end

    match "/soluciones", :to => 'mobile/soluciones#index', :as => 'soluciones'
    resources :solucion, controller: 'mobile/soluciones', :except => [:index]
    scope path: :solucion, :as => "solucion" do
    end


    match "/productos", :to => 'mobile/productos#index', :as => 'productos'
    resources :producto, controller: 'mobile/productos', :except => [:index]
    scope path: :producto, :as => "producto" do
    end

    match "/hotnow", :to => "mobile/productos#hotnow", :as => "hotnow"
    match "/bestsellers", :to => "mobile/productos#bestsellers", :as => "bestsellers"
    match "/lonuevo", :to => "mobile/productos#lonuevo", :as => "lonuevo"
    match "/sephorapicks", :to => "mobile/productos#favoritos", :as => "favoritos"

    match "/specials", :to => 'mobile/specials#index', :as => 'specials'
    scope path: :special, :as => "special" do
      match "/wallpapers", :to => "mobile/specials#wallpapers", :as => "wallpapers"
    end

    match "/usuarios", :to => 'mobile/usuarios#index', :as => 'usuarios'
    scope path: :usuario, :as => "usuario" do
      match 'logout(/:hash)', :to => 'mobile/usuarios#logout', :as => 'logout'
      match '/perfil', :to => "mobile/usuarios#perfil", :as => "perfil"
      match '/wishlist', :to => "mobile/usuarios#wishlist", :as => "wishlist"
      match '/bienvenido', :to => "mobile/usuarios#bienvenido", :as => "bienvenido"

      match  '/wishlist/add/:upc', :to => "usuarios#wishlist_add", :as => "wishlist_add"
      match  '/wishlist/del/:upc', :to => "usuarios#wishlist_del", :as => "wishlist_del"
    end

    match "/categorias", :to => 'mobile/categorias#index', :as => 'categorias'
    resources :categoria, controller: 'mobile/categorias', :except => [:index]
    scope path: :categoria, :as => "categoria" do
    end

    # mascarillas mobile
    get 'mascarillashidratantes', :to => 'mobile#mascarillashidratantes', as: :mascarillashidratantes
    get 'mascarillasantiedad', :to => 'mobile#mascarillasantiedad', as: :mascarillasantiedad
    get 'mascarillasmultibeneficio', :to => 'mobile#mascarillasmultibeneficio', as: :mascarillasmultibeneficio
    get 'mascarillasnocturnas', :to => 'mobile#mascarillasnocturnas', as: :mascarillasnocturnas

    # miraclecushion
    get 'miraclecushion', :to => 'mobile#miraclecushion', as: :miraclecushion

    # base contorno
    get 'base-contorno', :to => 'paginas#basecontorno', as: :basecontorno
    get 'base-contorno/foundation', :to => 'paginas#basecontorno_foundation', as: :basecontorno_foundation
    get 'base-contorno/foundation/concern', :to => 'paginas#basecontorno_foundation_concern', as: :basecontorno_foundation_concern
    get 'base-contorno/foundation/video/:tipo', :to => 'paginas#basecontorno_foundation_video', as: :basecontorno_foundation_video
    get 'base-contorno/contour', :to => 'paginas#basecontorno_contour', as: :basecontorno_contour
    get 'base-contorno/contour/concern', :to => 'paginas#basecontorno_contour_concern', as: :basecontorno_contour_concern
    get 'base-contorno/contour/video/:tipo', :to => 'paginas#basecontorno_contour_video', as: :basecontorno_contour_video

    get "loveisthereason", :to => 'twitter_tags#index', :as => "mobile_loveisthereason"
    get "sephoraholiday", :to => 'holiday#index', :as => "mobile_sephoraholiday"
    get "sharethelove", :to => 'holiday#quotes', :as => "mobile_sharethelove"

    match '/:seccion', :to => 'mobile/secciones#show'
  end

  #Usuarios
  devise_for :usuarios, controllers: {
    sessions: "usuarios/sessions",
    registrations: "usuarios/registrations",
    confirmations: "usuarios/confirmations",
    passwords: "usuarios/passwords",
    unlocks: "usuarios/unlocks"
  }

  get   'usuarios/lista', :to => 'usuarios#lista', :as => 'usuarios_lista'
  put   'usuario/actualizar/:id', :to => 'usuarios#actualizar', :as => 'usuario_actualizar'
  get   'usuario/usar_sesion/:id', :to => 'usuarios#usar_sesion', :as => 'usuario_usar_sesion'
  get   'logout(/:hash)', :to => 'usuarios#logout', :as => 'logout'
  get   'usuario/perfil', :to => "usuarios#perfil", :as => "usuario"
  get   'usuario/wishlist', :to => "usuarios#wishlist", :as => "usuario_wishlist"
  get   'usuario/bienvenido', :to => "usuarios#bienvenido", :as => "usuario_bienvenido"
  get   'usuario/wishlist/ver/:slug', :to => "usuarios#wishlist_ver", :as => "usuario_wishlist_ver"
  post  'usuario/wishlist/add/:upc', :to => "usuarios#wishlist_add", :as => "usuario_wishlist_add"
  post  'usuario/wishlist/del/:upc', :to => "usuarios#wishlist_del", :as => "usuario_wishlist_del"


  #
  get 'smashboxcovershotpalette', :to => 'paginas#smashboxcovershotpalette', as: :smashboxcovershotpalette

  # mascarillas
  #

  get 'facemask', :to => 'paginas#mascarillasantiedad', as: :mascarillasantiedad
  get 'eyemask', :to => 'paginas#mascarillasmultibeneficio', as: :mascarillasmultibeneficio
  get 'sleepingmask', :to => 'paginas#mascarillashidratantes', as: :mascarillashidratantes

  get 'mascarillasnocturnas', :to => 'paginas#mascarillasnocturnas', as: :mascarillasnocturnas

  # miraclecushion
  get 'miraclecushion', :to => 'paginas#miraclecushion', as: :miraclecushion

app/controllers/mobile/carrusel_controller.rb
class Mobile::CarruselController < MobileController
	def show
		@animation = AnimationCarousel.find_by_slug(params[:slug])
	end
end

app/controllers/mobile/categorias_controller.rb
class Mobile::CategoriasController < MobileController
	def show
    @marcas_seleccionadas = params[:marca].split(",").map{|m| m.to_i } unless params[:marca].nil?
    @categoria = Categoria.includes(:productos).by_slug(params[:id]).first

    
    subcategorias = @categoria.descendants rescue []
    @subcategorias = subcategorias.reject{|r| r.parent_id != @categoria.id }

    # para encontrar productos en categorías descendientes
    catmap = [@categoria.id] + @subcategorias.map{|s| s.id } rescue []
    @marcas_para_categoria = Categoria.encontrar_marcas(catmap)



    if params[:marca].blank?
      @productos = Producto.joins(:marca).publicados.padres.where(:categoria_id => catmap).order(("marcas.marca ASC"  if params[:ordenar] == "marca")).order(preciorder(params[:precio])).order('foto_file_name ASC').page(params[:page]).per(perparams(params[:ver]))
      @productoscount = Producto.publicados.padres.where(:categoria_id => catmap).order(preciorder(params[:precio])).count
    else
      @marca = Marca.find(@marcas_seleccionadas)
      @productos = Producto.publicados.padres.where(:marca_id => @marca.map{|m| m.id }, :categoria_id => catmap).order(preciorder(params[:precio])).page(params[:page]).per(perparams(params[:ver]))
      @productoscount = Producto.publicados.padres.where(:marca_id => @marca.map{|m| m.id }, :categoria_id => catmap).count
    end
  end

  def rebajas
    @marcas_seleccionadas = params[:marca].split(",").map{|m| m.to_i } unless params[:marca].nil?
    
    @categoria = (params[:categoria]) ? Categoria.includes(:productos).by_slug(params[:categoria]).first : nil
    
    if @categoria
      subcategorias = @categoria.descendants
      @subcategorias = subcategorias.reject{|r| r.parent_id != @categoria.id }
      catmap = [@categoria.id] + @subcategorias.map{|s| s.id }
      @marcas_para_categoria = Categoria.encontrar_marcas(catmap)
      if params[:marca].blank?
        @productos = Producto.joins(:marca).publicados.padres.where(:categoria_id => catmap).where("productos.descuento_porcentual != 0").order(("marcas.marca ASC"  if params[:ordenar] == "marca")).order(preciorder(params[:precio])).order('foto_file_name ASC').page(params[:page]).per(perparams(params[:ver]))
        @productoscount = Producto.publicados.padres.where(:categoria_id => catmap).where("productos.descuento_porcentual != 0").order(preciorder(params[:precio])).count
      else
        @marca = Marca.find(@marcas_seleccionadas)
        @productos = Producto.publicados.padres.where(:marca_id => @marca.map{|m| m.id }, :categoria_id => catmap).where("productos.descuento_porcentual != 0").order(preciorder(params[:precio])).page(params[:page]).per(perparams(params[:ver]))
        @productoscount = Producto.publicados.padres.where(:marca_id => @marca.map{|m| m.id }, :categoria_id => catmap).where("productos.descuento_porcentual != 0").count
      end
    else
      if params[:marca].blank?
        @productos = Producto.joins(:marca).publicados.padres.order(("marcas.marca ASC"  if params[:ordenar] == "marca")).where("productos.descuento_porcentual != 0").order(preciorder(params[:precio])).order('foto_file_name ASC').page(params[:page]).per(perparams(params[:ver]))
        @productoscount = Producto.joins(:marca).publicados.padres.order(("marcas.marca ASC"  if params[:ordenar] == "marca")).where("productos.descuento_porcentual != 0").count
      else
        @marca = Marca.find(@marcas_seleccionadas)
        @productos = Producto.publicados.padres.where(:marca_id => @marca.map{|m| m.id }).where("productos.descuento_porcentual != 0").order(preciorder(params[:precio])).page(params[:page]).per(perparams(params[:ver]))
        @productoscount = Producto.publicados.padres.where(:marca_id => @marca.map{|m| m.id }).where("productos.descuento_porcentual != 0").count
      end
      @categorias = Categoria.where(:id => Producto.pluck(:categoria_id).uniq)
    end
  end

  def obsequios
    cat = [41, 50, 64, 62, 63, 39]
    @productos = Producto.padres.rangodeprecios(params[:rango]).where(:categoria_id => cat, :publicado => true).order(preciorder(params[:precio])).page(params[:page]).per(perparams(params[:ver]))
    @productoscount = Producto.padres.rangodeprecios(params[:rango]).where(:categoria_id => cat, :publicado => true).count
  end
end

app/controllers/mobile/eventos_controller.rb
class Mobile::EventosController < MobileController
	def index
    #m = [78, 93, 75, 92, 79, 77, 76, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91]
    #n = m & Event.where({id: m}).pluck(:id)
    #@eventos = Event.where({id: n}).index_by(&:id).values_at(*n) rescue []
    @eventos = Event.all
    @tiendas = Tienda.all
  end

  def show
    @evento = Event.find(params[:id])
    @store_event = StoreEvent.where(:event_id => @evento.id)
  end
end

app/controllers/mobile/landings_controller.rb
class Mobile::LandingsController < MobileController

  def show
    @campaing_landing = CampaingLanding.find_by_vanity_url(params[:slug])
  end

	def fenty
    @campaing = Popup.find_by_campaing("fenty-beauty")
  end

  def beautyfair; end
  def masterclass; end
  def oasis; end
  def brow_collection; end
  def bellezaparallevar; end
  def beautyclasses; end
  def promocionessephora; end
  def regalaconamor; end
  def monterrey; end
  def smashboxcovershotpalette; end
  def promociondiadelasmadres; end
end

app/controllers/mobile/minimakeovers_controller.rb
class Mobile::MinimakeoversController < MobileController
end

app/controllers/mobile/modal_controller.rb
class Mobile::ModalController < ApplicationController
end

app/controllers/mobile/posts_controller.rb
class Mobile::PostsController < MobileController
	def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).order('created_at DESC').page(params[:page]).per(5)
    elsif params[:categoria]
      @posts = Post.where(:categoria_id => params[:categoria]).order('created_at DESC').page(params[:page]).per(5)
    else
      @posts = Post.order('created_at DESC').page(params[:page]).per(5)
    end

    @visitas = Post.order('visitas DESC').last(5)
  end

  def show
    @comment = Comment.new
    @ranking = Ranking.new
    @posts = Post.find params[:id]
    @posts.increment
    @visitas = Post.order('visitas DESC').last(5)
  end
end

app/controllers/mobile/soluciones_controller.rb
class Mobile::SolucionesController < MobileController
	def show
		@seccion = Seccion.by_slug(:soluciones)
    @subsecciones = Seccion.subsecciones(@seccion)

    @solucion = Seccion.subsecciones(@seccion, params[:id])
	end
end

app/helpers/mobile/categorias_helper.rb
module Mobile::CategoriasHelper
end

app/helpers/mobile/eventos_helper.rb
module Mobile::EventosHelper
end

app/helpers/mobile/marcas_helper.rb
module Mobile::MarcasHelper
	def chomp_desc(descripiton)
		descripiton.lines.map(&:chomp)
	end

	def catalogo_categorias(categorias)
		items = []
		categorias.each do |categoria|
			items << content_tag(
				:ul, 
				content_tag(
					:li,
					catalogo_categoria_item(categoria)
				)
			)
		end
		raw(items.join("\n"))
	end

	def catalogo_categoria_item(categoria)
		items = []
		items << content_tag(:a, categoria.nombre, {:href => categoria.slug})
		items << catalogo_categorias(categoria.children) if categoria.children.any?
		raw(items.join("\n"))
	end

	def embed(youtube_url)
    youtube_id = youtube_url.gsub("&feature=youtu.be", '').split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
  
end

app/helpers/mobile/minimakeovers_helper.rb
module Mobile::MinimakeoversHelper
end

app/helpers/mobile/modal_helper.rb
module Mobile::ModalHelper
end

app/views/mobile/layouts/_footer.html.haml
%ul#redes
	%li
		%a.yt{:href => "https://www.youtube.com/user/SephoraMex", :target => "_blank"}
	%li
		%a.fb{:href => "https://www.facebook.com/SephoraMX", :target => "_blank"}
	%li
		%a.tw{:href => "https://twitter.com/SephoraMX", :target => "_blank"}
	%li
		%a.it{:href => "http://instagram.com/sephoramx", :target => "_blank"}
	%li
		%a.pi{:href => "http://www.pinterest.com/sephoramx/", :target => "_blank"}
%ul#subfooter
	%li.aviso= link_to "Aviso privacidad", m_politicas_path
	%li= link_to "Contacto", "mailto:atencion@sephora.com", {:target => "_blank"}
	%li= link_to "Devoluciones", m_politicas_devoluciones_path
	.clearfix

app/views/mobile/layouts/_menu.html.haml
#menu.animated.fadeInDown
  %ul.submenu-list
    %li
      =link_to new_usuario_session_path do
        Mi cuenta
        %span.glyphicon.glyphicon-chevron-right

    %li
      =link_to m_tiendas_path do
        Tienda
        %span.glyphicon.glyphicon-chevron-right

    %li
      =link_to m_minimakeovers_path do
        Beauty Studio
        %span.glyphicon.glyphicon-chevron-right

    %li
      =link_to m_eventos_path do
        Eventos
        %span.glyphicon.glyphicon-chevron-right

    %li
      =link_to m_marcas_path do
        Marcas
        %span.glyphicon.glyphicon-chevron-right

    %li.list-container.visible
      = link_to '#' do
        Maquillaje
        %span.glyphicon.glyphicon-chevron-down.circled
      %ul.submenu
        %li
          %a{:href => "/mobile/categoria/rostro"} Rostro
        %li
          %a{:href => "/mobile/categoria/brochas-y-aplicadores"} Brochas y Aplicadores
        %li
          %a{:href => "/mobile/categoria/paletas-y-sets"} Paletas y Sets
        %li
          %a{:href => "/mobile/categoria/ojos"} Ojos
        %li
          %a{:href => "/mobile/categoria/labios"} Labios
        %li
          %a{:href => "/mobile/categoria/unas"} Uñas
        %li
          %a{:href => "/mobile/categoria/cuerpo"} Cuerpo
    %li.list-container.visible
      = link_to '#' do
        Skincare
        %span.glyphicon.glyphicon-chevron-down.circled
      %ul.submenu
        %li
          %a{:href => "/mobile/categoria/lip-balm-y-tratamientos"} Bálsamo Labial y Tratamientos
        %li
          %a{:href => "/mobile/categoria/bronceadores-y-autobronceadores"} Bronceadores y Autobronceadores
        %li
          %a{:href => "/mobile/categoria/suplementos"} Suplemento
        %li
          %a{:href => "/mobile/categoria/mascarillas-y-exfoliantes"} Mascarillas y Exfoliantes
        %li
          %a{:href => "/mobile/categoria/sets-de-inicio-y-regimenes"} Sets de Inicio y Regímenes
        %li
          %a{:href => "/mobile/categoria/limpiadores"} Limpiadores
        %li
          %a{:href => "/mobile/categoria/hidratantes"} Hidratantes
        %li
          %a{:href => "/mobile/categoria/tonicos-y-rociadores"} Tónicos y Rociadores
        %li
          %a{:href => "/mobile/categoria/tratamientos-para-el-rostro"} Tratamientos para el Rostro
        %li
          %a{:href => "/mobile/categoria/protector-solar"} Protector Solar
        %li
          %a{:href => "/mobile/categoria/cremas-para-ojos"} Cremas para Ojos
        %li
          %a{:href => "/mobile/categoria/removedor-de-vellos"} Removedor de Vellos
        %li
          %a{:href => "/mobile/categoria/bbcream"} BB & CC Creams
        %li
          %a{:href => "/mobile/categoria/aceites"} Aceites
    %li.list-container.visible
      = link_to '#' do
        Fragancias
        %span.glyphicon.glyphicon-chevron-down.circled
      %ul.submenu
        %li
          %a{:href => "/mobile/categoria/obsequios-y-sets"} Obsequios y Sets
        %li
          %a{:href => "/mobile/categoria/hombre"} Hombre
        %li
          %a{:href => "/mobile/categoria/mujer"} Mujer
        %li
          %a{:href => "/mobile/categoria/rollerball"} Rollerball
    %li.list-container.visible
      = link_to '#' do
        Baño/Cuerpo
        %span.glyphicon.glyphicon-chevron-down.circled
      %ul.submenu
        %li
          %a{:href => "/mobile/categoria/scrubs-y-exfolianes"} Exfoliantes
        %li
          %a{:href => "/mobile/categoria/obsequios-y-sets-6"} Obsequios y Sets
        %li
          %a{:href => "/mobile/categoria/manos-y-pies"} Manos y Pies
        %li
          %a{:href => "/mobile/categoria/celulitis-y-estrias"} Celulitis y Estrías
        %li
          %a{:href => "/mobile/categoria/hidratantes-bano-cuerpo"} Hidratantes
        %li
          %a{:href => "/mobile/categoria/limpiadores-bano-y-cuerpo"} Limpiadores Baño y Cuerpo
    %li.list-container.visible
      = link_to '#' do
        Cabello
        %span.glyphicon.glyphicon-chevron-down.circled
      %ul.submenu
        %li
          %a{:href => "/mobile/categoria/shampoo"} Shampoo
        %li
          %a{:href => "/mobile/categoria/acondicionador"} Acondicionador
        %li
          %a{:href => "/mobile/categoria/tratamientos-para-el-cabello"} Tratamientos para el Cabello
        %li
          %a{:href => "/mobile/categoria/productos-para-styling"} Productos para Styling
        %li
          %a{:href => "/mobile/categoria/herramientas"} Herramientas
        %li
          %a{:href => "/mobile/categoria/accesorios"} Accesorios
        %li
          %a{:href => "/mobile/categoria/cepillos-y-peines"} Cepillos y Peines
    %li.list-container.visible
      = link_to '#' do
        Accesorios
        %span.glyphicon.glyphicon-chevron-down.circled
      %ul.submenu
        %li
          %a{:href => "/mobile/categoria/bolsos-y-estuches"} Bolsos y Estuches
        %li
          %a{:href => "/mobile/categoria/brochas-y-aplicadores-maquillaje"} Brochas y Aplicadores
        %li
          %a{:href => "/mobile/categoria/herramientas-de-spa"} Herramientas de Spa
        %li
          %a{:href => "/mobile/categoria/manicure-y-pedicure"} Manicure y Pedicure
        %li
          %a{:href => "/mobile/categoria/pinzas-y-accesorios-de-cejas"} Pinzas y Accesorios de cejas
        %li
          %a{:href => "/mobile/categoria/rizadores-de-pestanas"} Rizadores de Pestañas
        %li
          %a{:href => "/mobile/categoria/sacapuntas"} Sacapuntas
        %li
          %a{:href => "/mobile/categoria/espejos"} Espejos
    %li.list-container.visible
      = link_to '#' do
        Hombres
        %span.glyphicon.glyphicon-chevron-down.circled
      %ul.submenu
        %li
          %a{:href => "/mobile/categoria/obsequios-y-sets-5"} Obsequios y Sets
        %li
          %a{:href => "/mobile/categoria/afeitado"} Afeitado
        %li
          %a{:href => "/mobile/categoria/humectantes-y-tratamientos"} Humectantes y Tratamientos
        %li
          %a{:href => "/mobile/categoria/cremas-de-ojos"} Cremas de Ojos
        %li
          %a{:href => "/mobile/categoria/cuerpo-y-ducha"} Cuerpo y Ducha'
    %li
      = link_to '/mobile/soluciones' do
        Soluciones
        %span.glyphicon.glyphicon-chevron-right
    %li
      =link_to '/mobile/posts' do
        Blog
        %span.glyphicon.glyphicon-chevron-right
:coffee
  $(document).ready ->
    $(".icono.menu").click ->
      $("#menu").toggleClass("visible")

    $(".list-container").click ->
      $(this).find(".submenu").toggleClass("visible")