config/routes.rb
Sephora::Application.routes.draw do

  #mobile
  scope path: :mobile, as: "m" do
    match "/", :to => 'mobile#home', :as => 'home'
    match "download", :to => "mobile#download", :as => "download"
    match 'politicas-de-privacidad', :to => 'mobile#politicas', :as => 'politicas'
    match 'politicas-de-devoluciones', :to => 'mobile#devoluciones', :as => 'politicas_devoluciones'
    match 'rebajas', :to => 'mobile/categorias#rebajas', :as => 'promociones_show'
    match 'obsequios', :to => 'mobile/categorias#obsequios', :as => 'obsequios'

    #carrousels
    match 'carrusel/:slug', to: "mobile/carrusel#show"
    match 'landing/:slug', to: "mobile/landings#show"

    match 'favorites(/:id)', :to => 'secciones#favorites', :as => 'favorites'

    #favoritoslabios
    match "/favoritoslabios", :to => 'mobile#favoritoslabios', :as => 'favoritoslabios'

    # favoritosmascarillas
    match "/favoritosmascarillas", :to => 'mobile#favoritosmascarillas', :as => 'favoritosmascarillas'

    # mascarillas
    get 'facemask', :to => 'mobile/secciones#mascarillasantiedad', as: :mascarillasantiedad
    get 'eyemask', :to => 'mobile/secciones#mascarillasmultibeneficio', as: :mascarillasmultibeneficio
    get 'sleepingmask', :to => 'mobile/secciones#mascarillashidratantes', as: :mascarillashidratantes

    get 'mascarillasingredientesnaturales', to: 'mobile/secciones#mascarillasingredientesnaturales', as: :mascarillasingredientesnaturales
    get 'beneficiosmascarillas', to: 'mobile/secciones#beneficiosmascarillas', as: :beneficiosmascarillas

    #marcas
    match "/marcas", :to => 'mobile/marcas#index', :as => 'marcas'
    resources :marca, controller: 'mobile/marcas', :except => [:index]
    scope path: :marca, :as => "marca" do
    end

    #popups
    resources :popups do
      collection do
        match 'subscribe', to: 'popups#subscribe', via: [:get, :post], as: :subscribe
        match 'campaing/:popup', to: 'popups#campaing', via: [:get], as: :campaing
      end
    end

    #Landings
    match "/fenty-beauty", to: "mobile/landings#fenty", via:[:get], as: "fenty"
    match "/beautyclasses", to: "mobile/landings#beautyclasses", via:[:get], as: "beautyclasses"
    match "/beautyfair", to: "mobile/landings#beautyfair", via: [:get, :post], as: "beautyfair"
    match "/masterclass", to: "mobile/landings#masterclass", via: [:get, :post], as: "masterclass"
    match "/veracruz", to: "mobile/landings#veracruz", via: [:get, :post], as: "veracruz"
    match "/opening", to: "mobile/landings#opening", via: [:get, :post], as: "opening"
    match '/oasis', :to => 'mobile/landings#oasis', via: [:get, :post], as: "oasis"
    match '/monterrey', :to => 'mobile/landings#monterrey', via: [:get, :post], as: "monterrey"
    match '/brow-collection', :to => 'mobile/landings#brow_collection', via: [:get, :post], as: "brow_collection"
    match '/bellezaparallevar', :to => 'mobile/landings#bellezaparallevar', via: [:get, :post], as: "bellezaparallevar"
    match '/promocionessephora', :to => 'mobile/landings#promocionessephora', via: [:get, :post], as: "promocionessephora"
    match '/regala-con-amor', :to => 'mobile/landings#regalaconamor', via: [:get, :post], as: "regalaconamor"
    match '/smashboxcovershotpalette', :to => 'mobile/landings#smashboxcovershotpalette', via: [:get, :post], as: "smashboxcovershotpalette"
    match '/cliniquecrayola', :to => 'mobile/landings#crayola', via: [:get, :post], as: "crayola"
    match '/promociondiadelasmadres', :to => 'mobile/landings#promociondiadelasmadres', via: [:get, :post], as: "promociondiadelasmadres"

    match "/lista_eventos", :to => 'mobile/eventos#index', :as => 'eventos'
    match "/eventos", :to => 'mobile/eventos#index', :as => 'eventos'
    resources :evento, controller: 'mobile/eventos', :except => [:index]
    scope path: :evento, :as => "evento" do
    end

    match "/tiendas", :to => 'mobile/tiendas#index', :as => 'tiendas'
    resources :tienda, controller: 'mobile/tiendas', :except => [:index]
    scope path: :tienda, :as => "tienda" do
    end

    match "/minimakeovers", :to => 'mobile/minimakeovers#index', :as => 'minimakeovers'
    match "/makeoverpersonalizado", :to => 'mobile/minimakeovers#index', :as => 'makeoverpersonalizado'
    match "/beautyunoauno", :to => 'mobile/minimakeovers#index', :as => 'beautyunoauno'
    match "/consultapersonalizadabelleza", :to => 'mobile/minimakeovers#index', :as => 'consultapersonalizadabelleza'
    resources :minimakeover, controller: 'mobile/minimakeovers', :except => [:index]
    scope path: :minimakeover, :as => "minimakeover" do
    end

    match "/posts", :to => 'mobile/posts#index', :as => 'posts'
    match "/posts/:id", :to => 'mobile/posts#show', :as => 'posts_show'
    resources :post, controller: 'mobile/posts', :except => [:index]
    scope path: :post, :as => "post" do
    end

    match "/soluciones", :to => 'mobile/soluciones#index', :as => 'soluciones'
    resources :solucion, controller: 'mobile/soluciones', :except => [:index]
    scope path: :solucion, :as => "solucion" do
    end


    match "/productos", :to => 'mobile/productos#index', :as => 'productos'
    resources :producto, controller: 'mobile/productos', :except => [:index]
    scope path: :producto, :as => "producto" do
    end

    match "/hotnow", :to => "mobile/productos#hotnow", :as => "hotnow"
    match "/bestsellers", :to => "mobile/productos#bestsellers", :as => "bestsellers"
    match "/lonuevo", :to => "mobile/productos#lonuevo", :as => "lonuevo"
    match "/sephorapicks", :to => "mobile/productos#favoritos", :as => "favoritos"

    match "/specials", :to => 'mobile/specials#index', :as => 'specials'
    scope path: :special, :as => "special" do
      match "/wallpapers", :to => "mobile/specials#wallpapers", :as => "wallpapers"
    end

    match "/usuarios", :to => 'mobile/usuarios#index', :as => 'usuarios'
    scope path: :usuario, :as => "usuario" do
      match 'logout(/:hash)', :to => 'mobile/usuarios#logout', :as => 'logout'
      match '/perfil', :to => "mobile/usuarios#perfil", :as => "perfil"
      match '/wishlist', :to => "mobile/usuarios#wishlist", :as => "wishlist"
      match '/bienvenido', :to => "mobile/usuarios#bienvenido", :as => "bienvenido"

      match  '/wishlist/add/:upc', :to => "usuarios#wishlist_add", :as => "wishlist_add"
      match  '/wishlist/del/:upc', :to => "usuarios#wishlist_del", :as => "wishlist_del"
    end

    match "/categorias", :to => 'mobile/categorias#index', :as => 'categorias'
    resources :categoria, controller: 'mobile/categorias', :except => [:index]
    scope path: :categoria, :as => "categoria" do
    end

    # mascarillas mobile
    get 'mascarillashidratantes', :to => 'mobile#mascarillashidratantes', as: :mascarillashidratantes
    get 'mascarillasantiedad', :to => 'mobile#mascarillasantiedad', as: :mascarillasantiedad
    get 'mascarillasmultibeneficio', :to => 'mobile#mascarillasmultibeneficio', as: :mascarillasmultibeneficio
    get 'mascarillasnocturnas', :to => 'mobile#mascarillasnocturnas', as: :mascarillasnocturnas

    # miraclecushion
    get 'miraclecushion', :to => 'mobile#miraclecushion', as: :miraclecushion

    # base contorno
    get 'base-contorno', :to => 'paginas#basecontorno', as: :basecontorno
    get 'base-contorno/foundation', :to => 'paginas#basecontorno_foundation', as: :basecontorno_foundation
    get 'base-contorno/foundation/concern', :to => 'paginas#basecontorno_foundation_concern', as: :basecontorno_foundation_concern
    get 'base-contorno/foundation/video/:tipo', :to => 'paginas#basecontorno_foundation_video', as: :basecontorno_foundation_video
    get 'base-contorno/contour', :to => 'paginas#basecontorno_contour', as: :basecontorno_contour
    get 'base-contorno/contour/concern', :to => 'paginas#basecontorno_contour_concern', as: :basecontorno_contour_concern
    get 'base-contorno/contour/video/:tipo', :to => 'paginas#basecontorno_contour_video', as: :basecontorno_contour_video

    get "loveisthereason", :to => 'twitter_tags#index', :as => "mobile_loveisthereason"
    get "sephoraholiday", :to => 'holiday#index', :as => "mobile_sephoraholiday"
    get "sharethelove", :to => 'holiday#quotes', :as => "mobile_sharethelove"

    match '/:seccion', :to => 'mobile/secciones#show'
  end

  #Usuarios
  devise_for :usuarios, controllers: {
    sessions: "usuarios/sessions",
    registrations: "usuarios/registrations",
    confirmations: "usuarios/confirmations",
    passwords: "usuarios/passwords",
    unlocks: "usuarios/unlocks"
  }

  get   'usuarios/lista', :to => 'usuarios#lista', :as => 'usuarios_lista'
  put   'usuario/actualizar/:id', :to => 'usuarios#actualizar', :as => 'usuario_actualizar'
  get   'usuario/usar_sesion/:id', :to => 'usuarios#usar_sesion', :as => 'usuario_usar_sesion'
  get   'logout(/:hash)', :to => 'usuarios#logout', :as => 'logout'
  get   'usuario/perfil', :to => "usuarios#perfil", :as => "usuario"
  get   'usuario/wishlist', :to => "usuarios#wishlist", :as => "usuario_wishlist"
  get   'usuario/bienvenido', :to => "usuarios#bienvenido", :as => "usuario_bienvenido"
  get   'usuario/wishlist/ver/:slug', :to => "usuarios#wishlist_ver", :as => "usuario_wishlist_ver"
  post  'usuario/wishlist/add/:upc', :to => "usuarios#wishlist_add", :as => "usuario_wishlist_add"
  post  'usuario/wishlist/del/:upc', :to => "usuarios#wishlist_del", :as => "usuario_wishlist_del"


  #
  get 'smashboxcovershotpalette', :to => 'paginas#smashboxcovershotpalette', as: :smashboxcovershotpalette

  # mascarillas
  #

  get 'facemask', :to => 'paginas#mascarillasantiedad', as: :mascarillasantiedad
  get 'eyemask', :to => 'paginas#mascarillasmultibeneficio', as: :mascarillasmultibeneficio
  get 'sleepingmask', :to => 'paginas#mascarillashidratantes', as: :mascarillashidratantes

  get 'mascarillasnocturnas', :to => 'paginas#mascarillasnocturnas', as: :mascarillasnocturnas

  # miraclecushion
  get 'miraclecushion', :to => 'paginas#miraclecushion', as: :miraclecushion

app/models/marca.rb
class Marca < ActiveRecord::Base
  attr_accessor :marca, :descripcion, :slug, :logo, :promo, :behindthebrand, :remove_promo, :remove_logo, :video, :vista
  attr_accessor :logo, :promo, :remove_promo, :remove_logo
  default_scope :order => "marca ASC"

  scope :con_productos, -> { joins(:productos).where('productos.publicado = TRUE').group('marcas.id').having('count(productos.id) > 0') }

  scope :long, joins(:productos).
    select('marcas.id').
    group('marcas.id').
    having('count(productos.id) > 0')

  has_attached_file :logo, {
    :styles => { :grande => "375x65>", :normal => "200x57>", :mini => "100x29>" }
  }.merge(PAPERCLIP_STORAGE_OPTIONS)

  has_attached_file :promo, {
    :styles => { :grande => "266x266>", :normal => "170x170>", :mini => "100x100>" }
  }.merge(PAPERCLIP_STORAGE_OPTIONS)

  has_many :productos, inverse_of: :marca

  has_many :marca_producto
  has_many :featured, :through => :marca_producto, :class_name => "Producto", :source => :producto

  has_one :landing

  validate :validar

  before_save do
    self.slug = self.marca.parameterize if new_record?
    self.promo = nil if self.remove_promo=="1"
    self.logo = nil if self.remove_logo=="1"
  end

  def self.to_csv
    csv_string = CSV.generate do |csv|
      csv << ["id", "marca", "descripcion", "slug", "logo", "promo", "behindthebrand", "video"]
      all.each do |marca|
        csv << [marca.id, marca.marca, marca.descripcion, marca.slug, marca.logo(:grande), marca.promo, marca.behindthebrand, marca.video]
      end
    end
  end

  def self.mas_buscadas
    marcas = Marca.find([52, 41, 2, 63, 57])
    marcas
  end

  def validar
    errors.add :marca, "Escribe una marca" unless self.marca.parameterize.length > 1
  end
end

app/controllers/marcas_controller.rb
require "csv"

class MarcasController < ApplicationController
  before_filter :set_marca, :only => [:incrementar_vistas, :show]
  before_filter :incrementar_vistas, :only => [:show]
  before_filter :get_parent_categories, :only => [:show]

  def index
    @marcas = Marca.all
    authorize! :manage, @marca
  end

  def new
    @marca = Marca.new
    authorize! :manage, @marca
  end

  def create
    @marca = Marca.new params[:marca]
    authorize! :manage, @marca
    if @marca.save
      redirect_to marca_ver_path(@marca.slug)
    else
      render :new
    end
  end

  def edit
    @marca = Marca.find params[:id]
    authorize! :manage, @marca
  end

  def update
    @marca = Marca.find params[:id]
    authorize! :manage, @marca
    if @marca.update_attributes params[:marca]
      redirect_to marca_ver_path(@marca.slug)
    else
      render :edit
    end
  end

  def show
    @careoca_makeup = Producto.where(:upc => ["3378872080497","3378872080473", "3378872080572","3378872080442"])
    @careoca_bath = Producto.where(:upc => ["3378872079781", "3378872079743", "3378872079750", "3378872079767"])
    f_cat = []
    @f_parent = []

    pic = Producto.includes(:categoria).where(:marca_id => @marca.id).where(:publicado => true);
    pic.each do |t| f_cat << t.categoria.nombre rescue nil end
    @categorias = f_cat.uniq.sort

    @parent_categories.each do |pc|
      child_cats = Categoria.where(:parent_id => pc.id).pluck(:id) rescue []
      child_cats << pc.id
      p_count = pic.where(:categoria_id => child_cats).where(:parent_id => nil).count
      @f_parent << {:id => pc.id, :categoria => pc.nombre, :product_count => p_count, :slug => pc.slug}
    end
  end

  def destroy
    Marca.delete params[:id]
    authorize! :manage, :destroy
    redirect_to marcas_path
  end

  # Vínculos

  def vincular
    marca = Marca.find params[:id]
    authorize! :manage, marca
    vinculo = marca.marca_producto.build params[:marca_producto]
    if vinculo.valid?
      vinculo.save
    end
    redirect_to edit_marca_path(marca.id)
  end

  def desvincular
    marca = Marca.find params[:id]
    authorize! :manage, marca
    marca_producto = marca.marca_producto.find params[:marca_producto]

    if check_minihash(marca_producto, params[:hash])
      marca_producto.destroy
    end

    redirect_to edit_marca_path(marca.id)
  end

  def producto_editar
    @marca = Marca.find params[:id]
    authorize! :manage, @marca
    @marca_producto = @marca.marca_producto.find params[:v_id]
  end

  def producto_update
    marca = Marca.find params[:id]
    authorize! :manage, marca
    marca_producto = marca.marca_producto.find(params[:v_id])
    marca_producto.update_attributes params[:marca_producto]
    if marca_producto.valid?
      marca_producto.save
      redirect_to marca_editar_producto_path(marca.id, marca_producto.id)
    else
      render :producto_editar
    end
  end

  def actualizar_orden
    vinculos = params[:vinculo_id]
    orden = (0...vinculos.size)

    marcaProducto.update( vinculos, orden.map{|o| { :orden => o }}).reject { |p| p.errors.empty? }

    render :text => orden.to_a
  end


  def export_to_csv
    if params[:pass] == "outofthebox14"
      respond_to do |format|
        format.html
        format.csv { render text: Marca.to_csv}
      end
    end
  end

  private

  def incrementar_vistas
    vista = @marca.vista || 0
    vista += 1
    @marca.update_attribute(:vista, vista)
  end

  def set_marca
    @marca = Marca.includes(:marca_producto, :featured).where(:slug => params[:slug]).first
  end

  def get_parent_categories
    @parent_categories = Categoria.where(:parent_id => nil)
  end
end

app/controllers/mobile/marcas_controller.rb
class Mobile::MarcasController < MobileController
	before_filter :set_marca_by_slug, :only => [:show]
	before_filter :get_parent_categories, :only => [:show]

	def index
		@marcas = Marca.find(:all, :order =>"marca ASC").group_by{|u| u.marca[0].upcase}
	end

	def show
		f_cat = []
    @f_parent = []

    pic = Producto.includes(:categoria).where(:marca_id => @marca.id).where(:publicado => true);
    pic.each do |t| f_cat << t.categoria.nombre rescue nil end
    @categorias = f_cat.uniq.sort

    @parent_categories.each do |pc|
      child_cats = Categoria.where(:parent_id => pc.id).pluck(:id) rescue []
      child_cats << pc.id
      p_count = pic.where(:categoria_id => child_cats).where(:parent_id => nil).count
      @f_parent << {:id => pc.id, :categoria => pc.nombre, :product_count => p_count, :slug => pc.slug}
     end
	end
	
	private

	def set_marca_by_slug
		slug = params[:id] rescue nil
		if slug
			@marca = Marca.find_by_slug(slug)
		else
			redirect_to m_marcas_path
		end
	end

	def get_parent_categories
		@parent_categories = Categoria.where(:parent_id => nil)
	end

	def get_descendants(parent_categories)
		cats = []
		parent_categories.each do |pc|
			categoria = pc
			childrens = (pc.children.any?) ? get_descendants(pc.children) : nil
			cats << {categoria:categoria, childrens: childrens}
		end
		cats
	end

	def get_marca_categories
		@productos_en_categoria = Producto.includes(:categoria).where(:publicado => true, :marca_id => @marca.id)
		@categorias = @productos_en_categoria.map{|c| c.categoria}.uniq.sort
	end
end

app/helpers/mobile/marcas_helper.rb
module Mobile::MarcasHelper
	def chomp_desc(descripiton)
		descripiton.lines.map(&:chomp)
	end

	def catalogo_categorias(categorias)
		items = []
		categorias.each do |categoria|
			items << content_tag(
				:ul, 
				content_tag(
					:li,
					catalogo_categoria_item(categoria)
				)
			)
		end
		raw(items.join("\n"))
	end

	def catalogo_categoria_item(categoria)
		items = []
		items << content_tag(:a, categoria.nombre, {:href => categoria.slug})
		items << catalogo_categorias(categoria.children) if categoria.children.any?
		raw(items.join("\n"))
	end

	def embed(youtube_url)
    youtube_id = youtube_url.gsub("&feature=youtu.be", '').split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
  
end

app/views/marcas/edit.html.haml
-provide :title, 'Editar Marca'
%h2 Editar Marca
=form_for @marca do |f|
  %p
    =form_error @marca, :marca
    =f.labelbrtext "Marca", :marca, :class => "big full"
  %p
    =form_error @marca, :descripcion
    =f.labelbrtextarea "Descripción", :descripcion, :class => "full"
  %p
    =form_error @marca, :behindthebrand
    =f.labelbrtextarea "Detrás de la marca (opcional)", :behindthebrand, :class => "full"
  %p
    = f.labelbrtext "URL Video", :video, :placeholder => 'http://'
  %p
    = f.label :logo, "Logo"
    %br
    = f.file_field :logo
  - unless @marca.logo_file_name.nil? 
    %p
      = image_tag @marca.logo.url(:mini)
    = f.check_box :remove_logo
    = f.label "¿Quitar foto?"
  %p
    = f.label :promo, "Promo"
    %br
    = f.file_field :promo
  - unless @marca.promo_file_name.nil? 
    %p
      = image_tag @marca.promo.url(:mini)
    = f.check_box :remove_promo
    = f.label "¿Quitar foto?"
  %p.rgt
    =f.submit "Editar"


%h3 Productos destacados
- if (marca_productos = @marca.marca_producto) and marca_productos.any?
  %ul.productos-vinculados{ :'data-cambiar-orden-url' => '/marcas/actualizar_orden' }
    - marca_productos.each do |marca_producto|
      - producto = marca_producto.producto
      %li.vinculo-producto{ :'data-vinculo-id' => marca_producto.id }
        %h6.inline
          #{producto.nombre}
        %small
          %ul.nolist.nobullet.seplist.inline
            %li
              %a{ :href => marca_desvincular_producto_path(@marca.id, marca_producto.id, mini_hash(marca_producto)) }<
                Desvincular
            %li
              %a{ :href => marca_editar_producto_path(@marca.id, marca_producto.id) }<
                Editar
        - unless marca_producto.descripcion.empty?
          .descripcion
            = simple_format marca_producto.descripcion
- else
  .empty
    %h5 No hay productos

= form_for :busqueda, :url => productos_busqueda_path, :html => { :class => "widget-seccion-producto-vincular" } do |f|
  %p
    = f.text_field "q", :type => "search", :class => "big", :placeholder => "Buscar productos"
    = f.submit "Buscar"
  .resultados

= form_for (producto = @marca.marca_producto.build), :url => marca_vincular_producto_path(@marca.id), :html => { :class => "widget-seccion-producto-form" } do |f|
  %h3
    %small Vincular producto
    »
    %span.tmpl-producto-nombre
  = f.hidden_field :producto_id
  %p
    = form_error producto, :descripcion
    = f.labelbrtextarea "Descripción", :descripcion, :class => "full"
  %p.rgt
    = f.submit! "Agregar"

app/views/marcas/index.html.haml
%ul
  %li
    =link_to "nueva marca", new_marca_path
-if @marcas and @marcas.any?
  %h3 Nuestras Marcas
  %ul
    -@marcas.each do |marca|
      %li
        [#{marca.id}]
        =link_to marca.marca, marca_ver_path(marca.slug)
        
        %small
          -# =button_to "borrar", marca, :method => :delete
          =link_to "editar", edit_marca_path(marca.id)

app/views/marcas/new.html.haml
-provide :title, 'Registrar Marca'
%h2 Registrar Marca
=form_for @marca do |f|
  %p
    =form_error @marca, :marca
    =f.labelbrtext "Marca", :marca, :class => "big full"
  %p
    =form_error @marca, :descripcion
    =f.labelbrtextarea "Descripción", :descripcion, :class => "full"
  %p
    =form_error @marca, :behindthebrand
    =f.labelbrtextarea "Detrás de la marca (opcional)", :behindthebrand, :class => "full"
  %p
    = f.labelbrtext "URL Video", :video, :placeholder => 'http://'
  %p
    = f.label :logo, "Logo"
    %br
    = f.file_field :logo
  - unless @marca.logo_file_name.nil? 
    %p
      = image_tag @marca.logo.url(:mini)
  %p
    = f.label :promo, "Promo"
    %br
    = f.file_field :promo
  - unless @marca.promo_file_name.nil? 
    %p
      = image_tag @marca.promo.url(:mini)
  %p.rgt
    =f.submit "Registrar"

app/views/marcas/producto_editar.html.haml
%section#marca-producto-editar
  = form_for @marca_producto, :url => marca_editar_producto_path(@marca.id, @marca_producto.id) do |f|
    %p
      = f.labelbrtextarea "Descripción", :descripcion, :class => "full"
    %p.rgt
      = f.submit "Actualizar"

app/views/marcas/show.html.haml
- provide :titulo, @marca.marca
- provide :url, "http://sephora.com.mx/marca/#{@marca.slug}"
- provide :imagen, @marca.logo.url(:normal)
-unless @marca.descripcion.nil?
  - provide :descripcion, @marca.descripcion.html_safe[0..160]
%section#marca
  .table.full
    .contizq.tcell.t20
      %ul
        - unless @parent_categories.empty?
          - @f_parent.each do |pc|
            - slug_c = pc[:slug]
            - unless pc[:product_count] == 0
              %li.first
                - cat_link = categoria_ver_path(slug_c)+"?marca=#{@marca.id}"
                = link_to "#"  do 
                  ="#{pc[:categoria]} (#{pc[:product_count]})"
                  %span.glyphicon.glyphicon-plus
                - @cats = Categoria.find(pc[:id]).children rescue []
                - unless @cats.empty?
                  %ul
                    - @cats.each do |t|
                      - slug = Categoria.find(t).slug
                      %li.second
                        = link_to t.nombre, categoria_ver_path(slug)+"?marca=#{@marca.id}"
        - unless @marca.behindthebrand.empty?
          %li.behindbutton
            Detrás de la marca
    .contder.tcell.t80
      - unless @marca.landing.nil?
        .banner-marcas
          =link_to image_tag(@marca.landing.banner), @marca.landing.link, {:class=>"banner_landing"}
      - unless @marca.logo_file_name.nil?
        .logo-marca
          = image_tag @marca.logo.url(:grande)
      .table.full
        .tcell.t65
          %p
            =@marca.descripcion.gsub(/(\r|\n)+/, '<br />').html_safe
          - unless @marca.behindthebrand.empty?
            %p.behindbutton
              Detrás de la marca ▼
        .tcell.t35.vmiddle
          - unless @marca.promo_file_name.nil?
            = image_tag @marca.promo.url(:grande)

      - unless @marca.video.nil? || @marca.video.empty?
        - video = @marca.video.scan(/(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/ ]{11})/i)
        .video
          ="<iframe width='640' height='360' src='http://www.youtube.com/embed/#{video[0][0]}?rel=0' frameborder='0' allowfullscreen></iframe>".html_safe

      - unless @marca.behindthebrand.empty?
        .table.full.behindthebrand
          %h3 DETRÁS DE LA MARCA
          %p
            =@marca.behindthebrand.gsub(/(\r|\n)+/, '<br />').html_safe

      - unless @marca.marca_producto.count == 0
        %h3 EXPLORA LA MARCA
        #best-catalogo.catalogo
          %h4.title
            BEST SELLERS
          #slider-wrap
            %ul.nobullet.nolist
              - @marca.marca_producto.each do |marca_producto|
                %li
                  .imagen
                    = link_to image_tag(marca_producto.producto.foto(:normal)), producto_ver_path(marca_producto.producto.slug)
                  %h5.marca
                    = marca_producto.producto.marca.marca.upcase
                  %h5
                    = link_to marca_producto.producto.nombre.split(' ').map {|w| w.capitalize }.join(' '), producto_ver_path(marca_producto.producto.slug)
                  %p
                    -if marca_producto.producto.tiene_descuento
                      %span.precio_original
                        #{number_to_currency(marca_producto.producto.precio, :precision => 0)}
                      %span
                        &nbsp; - &nbsp;
                      %span.tiene_descuento
                        #{number_to_currency(marca_producto.producto.descuento, :precision => 0)}
                    -else
                      #{number_to_currency(marca_producto.producto.precio, :precision => 0)}

:coffee
  $(document).ready ->
    $("ul li.first").click ->
      $(this).find("ul").toggleClass("visible")
      $(this).find("span").toggleClass("glyphicon-plus").toggleClass("glyphicon-minus")