config/routes.rb
  get '/makeoverpersonalizado', :to => 'paginas#servicios_completos', :as => 'servicioscompletos'
  get '/lista_eventos', :to => 'paginas#lista_eventos', :as => 'eventos'
  get '/beautyunoauno', :to => 'paginas#beauty', :as => 'beautyunoauno'

  get 'sephoragifts' => 'paginas#sephoragifts'

  #MARCJACOBS
  get "marc-jacobs-beauty/home", :to => "marcjacobs#home", :as => 'marcjacobs'
  get "marc-jacobs-beauty/", :to => "marcjacobs#intro", :as => 'marc_intro'
  get "marc-jacobs-beauty/ojos", :to => "marcjacobs#ojos", :as => 'marc_ojos'
  get "marc-jacobs-beauty/labios", :to => "marcjacobs#labios", :as => 'marc_labios'
  get "marc-jacobs-beauty/unas", :to => "marcjacobs#unas", :as => 'marc_unas'
  get "marc-jacobs-beauty/rostro", :to => "marcjacobs#rostro", :as => 'marc_rostro'
  get "marc-jacobs-beauty/favoritos", :to => "marcjacobs#favoritos", :as => 'marc_favs'
  get "marc-jacobs-beauty/look", :to => "marcjacobs#look", :as => 'marc_look'
  get "marc-jacobs-beauty/catalogo", :to => "marcjacobs#catalogo", :as => 'marc_catalogo'


  #wishlist
  get "wishlist", :to => 'wishlist#index', :as => "wishlist"
  post "wishlist", :to => 'wishlist#index', :as => "wishlist"

  get "wishlist/admin/", :to => 'wishlist#admin', :as => "wishlist_admin"
  post "wishlist/admin/", :to => 'wishlist#admin', :as => "wishlist_admin"

  get "wishlist/lista/", :to => 'wishlist#lista', :as => "wishlist_lista"
  post "wishlist/lista/", :to => 'wishlist#lista', :as => "wishlist_lista"


  get "wishlist/nuevo/(:uid)/(:post_id)/(:producto1)/(:producto2)/(:producto3)/(:producto4)/(:producto5)/(:token)", :to => "wishlist#nuevo", :as => "wishlist_nuevo"
  post "wishlist/nuevo/(:uid)/(:post_id)/(:producto1)/(:producto2)/(:producto3)/(:producto4)/(:producto5)/(:token)", :to => "wishlist#nuevo", :as => "wishlist_nuevo"

  get "wishlist/ver/(:uid)", :to => "wishlist#ver", :as => "wishlist_ver"
  post "wishlist/ver/(:uid)", :to => "wishlist#ver", :as => "wishlist_ver"

  get "wishlist/error", :to => 'wishlist#index', :as => "wishlist_error"
  post "wishlist/error", :to => 'wishlist#index', :as => "wishlist_error"

  get "wishlist/mi_lista/(:uid)/(:token)", :to => 'wishlist#user', :as => "wishlist_user"
  post "wishlist/mi_lista/(:uid)/(:token)", :to => 'wishlist#user', :as => "wishlist_user"

  #admin
  get "/admin/clear", :to => "application#clear_cache", :as => "clear_cache"


  #Comunicados
  get   'comunicado', :to => 'paginas#comunicado', :as => 'comunicado'

  #sephora_tips
  get "sephora_tips", :to => 'sephora_tips#index', :as => "sephora_tips"
  post "sephora_tips", :to => 'sephora_tips#index', :as => "sephora_tips"
  post 'sephora_tips/send', :to => 'sephora_tips#post_tip', :as => 'post_sephora_tips'

  get "sephora_tips/admin/", :to => 'sephora_tips#admin', :as => "sephora_tips_admin"
  get "sephora_tips/admin/download", :to => 'sephora_tips#download', :as => "sephora_tips_download"



  #tabs
  get "tabs/sephoragifts", :to => "tabs#sephoragifts", :as => "sephoragifts"
  post "tabs/sephoragifts", :to => "tabs#sephoragifts", :as => "sephoragifts"


  #blog
  resources :posts
  get 'posts/tags/:tag', :to => 'blog#index', :as => 'tag'
  post '/posts/:id/comment', :to => 'posts#comment', :as => 'comment_post'
  post 'posts/:id/ranking', :to => 'posts#ranking', :as => 'ranking_post'



  resources :landings
  resources :events, controller: "administracion/events", except: :index
  resources :store_events, controller: "administracion/store_events", except: :index
  resources :banners, controller: "administracion/banners"
  resources :campaing_landings, controller: "administracion/campaing_landings"

  #carruseles
  resources :animation_carousels, controller: "administracion/animation_carousels"
  resources :carousels, controller: "administracion/carousels"

  match 'carrusel/:slug', to: "carrusel#show", as: :ver_carrusel
  match 'landing/:slug', to: "campaing_landings#show", as: :ver_landing

  resources :popups do
    collection do
      match 'subscribe', to: 'popups#subscribe', via: [:get, :post], as: :subscribe
      match 'campaing/:popup', to: 'popups#campaing', via: [:get], as: :campaing
    end
  end
  resources :animations, controller: "administracion/animations"
  scope path: :administracion, as: "admin" do

    resources :landings, except: :index
    resources :events, except: :index, controller: "administracion/events"
    resources :banners, controller: "administracion/banners"
    resources :popups, controller: "administracion/popups"
    resources :campaing_landings, controller: "administracion/campaing_landings"
    resources :animations, controller: "administracion/animations"
    resources :store_events, except: :index, controller: "administracion/store_events"
    resources :carousels, controller: "administracion/carousels"
    resources :animation_carousels, controller: "administracion/animation_carousels" do
      match :add_carousel, to: 'administracion/animation_carousels#add_carousel', via: [:put, :post]
    end

    match 'photogram/suscribe', to: 'administracion/photogram#suscribe', via: :get
    match 'photogram/suscribe', to: 'administracion/photogram#fetch', via: :post

    resources :photogram, except: :index, controller: "administracion/photogram"

    match 'landings', to: 'administracion#landings', via: :get
    match 'events', to: 'administracion#events', via: :get
    match 'store_events', to: 'administracion#store_events', via: :get
    match 'photogram', to: 'administracion#photogram', via: :get

    scope "/productos" do 
      match 'prices', to: 'administracion#prices', via: :get
      match 'update_prices', to: 'administracion#update_prices', via: :post

      match 'descontinuados', to: 'administracion#descontinuados', via: :get
      match 'update_descontinuados', to: 'administracion#update_descontinuados', via: :post

      match 'files', to: 'administracion#files', via: :get
      match 'upload_file', to: 'administracion#upload_file', via: :post
    end
  end

  #brand-minisite
  get 'sephora-collection/', :to => 'sephora_collection#index', :as => 'sephora_collection_index'
  get 'sephora-collection/seccion/:interna', :to => 'sephora_collection#interna', :as => 'sephora_collection_interna'
  get 'sephora-collection/rouge-land', :to => 'sephora_collection#rouge_land', :as => 'sephora_collection_rouge_land'
  get 'sephora-collection/foundation-land', :to => 'sephora_collection#foundation_land', :as => 'sephora_collection_foundation_land'
  get 'sephora-collection/outrageus-land', :to => 'sephora_collection#outrageus_land', :as => 'sephora_collection_outrageus_land'
  get 'sephora-collection/promociones', :to => 'sephora_collection#promociones', :as => 'sephora_collection_promociones'

  # ajax call
  get "sephora-collection/squares/:interna", :to => 'sephora_collection#load_squares', :as => "sephora_collection_loadsquares"


  # /mascarillasingredientesnaturales
  match "/mascarillasingredientesnaturales", to: "paginas#mascarillasingredientesnaturales", via: [:get, :post], as: "mascarillasingredientesnaturales"
  match "/beneficiosmascarillas", to: "paginas#beneficiosmascarillas", via: [:get, :post], as: "beneficiosmascarillas"



  # friends and family
  get 'friendsandfamily/', :to => 'friendsandfamily#index', :as => 'friendsandfamily_index'
  post 'friendsandfamily/code', :to => 'friendsandfamily#code', :as => 'friendsandfamily_code'
  get 'friendsandfamily/gracias/:id', :to => 'friendsandfamily#gracias', :as => 'friendsandfamily_gracias'
  get 'friendsandfamily/ya_descargaste', :to => 'friendsandfamily#ya_descargaste', :as => 'friendsandfamily_ya_descargaste'
  get 'friendsandfamily/delete_cookie', :to => 'friendsandfamily#delete_cookie', :as => 'friendsandfamily_delete_cookie'

  match "/beautyfair", to: "paginas#beautyfair", via: [:get, :post], as: "beautyfair"
  match "/masterclass", to: "paginas#masterclass", via: [:get, :post], as: "masterclass"
  match "/veracruz", to: "paginas#veracruz", via: [:get, :post], as: "veracruz"
  match "/opening", to: "paginas#opening", via: [:get, :post], as: "opening"
  match '/oasis', :to => 'paginas#oasis', via: [:get, :post], as: "oasis"
  match '/brow-collection', :to => 'paginas#brow_collection', via: [:get, :post], as: "brow_collection"
  match '/5aniv', :to => 'paginas#celebra_con_nosotros', via: [:get, :post], as: "celebra_con_nosotros"
  match '/promocionessephora', :to => 'paginas#promocionessephora', via: [:get, :post], as: "promocionessephora"
  match '/regala-con-amor', :to => 'paginas#regalaconamor', via: [:get, :post], as: "regalaconamor"

  match '/cliniquecrayola', :to => 'paginas#crayola', via: [:get, :post], as: "crayola"
  match '/promociondiadelasmadres', :to => 'paginas#promociondiadelasmadres', via: [:get, :post], as: "promociondiadelasmadres"


  scope :animacion do
    #match "/commodity", to: "animacion#commodity", via:[:get], as: "commodity"
    #match "/clean", to: "animacion#clean", via:[:get], as: "clean"
    #match "/tocca", to: "animacion#tocca", via:[:get], as: "tocca"
    #match "/nest", to: "animacion#nest", via:[:get], as: "nest"
    match "/beautyclasses", to: "animacion#beautyclasses", via:[:get], as: "beautyclasses"
  end

  #match "/fenty-beauty", to: "paginas#fenty", via:[:get], as: "fenty"

  scope '/beautyfair2016', as: "beautyfair" do
    match '/', :to => 'beautyfair#home', via: [:get, :post], as: "home"
    match '/tour', :to => 'beautyfair#tour', via: [:get, :post], as: "tour"
    match '/playa', :to => 'beautyfair#playa', via: [:get, :post], as: "playa"
    match '/antea', :to => 'beautyfair#antea', via: [:get, :post], as: "antea"
    match '/andares', :to => 'beautyfair#andares', via: [:get, :post], as: "andares"
    match '/antara', :to => 'beautyfair#antara', via: [:get, :post], as: "antara"
  end

  match "/bellezaparallevar", to: "animacion#index", via:[:get], as: "bellezaparallevar"

  match "/google73f11619b8774ed8.html", to: "paginas#verify_google_console", via:[:get], as: "verify_google_console"

  #sitemap

app/controllers/administracion/animation_carousels_controller.rb
class Administracion::AnimationCarouselsController < ApplicationController
  layout "administracion"
  
  # GET /animation_carousels
  # GET /animation_carousels.json
  def index
    @animation_carousels = AnimationCarousel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @animation_carousels }
    end
  end

  # GET /animation_carousels/1
  # GET /animation_carousels/1.json
  def show
    @animation_carousel = AnimationCarousel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @animation_carousel }
    end
  end

  # GET /animation_carousels/new
  # GET /animation_carousels/new.json
  def new
    @animation_carousel = AnimationCarousel.new
    #@animation_carousel.carousels << Carousel.new if @animation_carousel.carousels.count == 0
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @animation_carousel }
    end
  end

  # GET /animation_carousels/1/edit
  def edit
    @animation_carousel = AnimationCarousel.find(params[:id])
    @carousel = Carousel.new({animation_carousel: @animation_carousel})
  end

  # POST /animation_carousels
  # POST /animation_carousels.json
  def create
    @animation_carousel = AnimationCarousel.new(params[:animation_carousel])

    respond_to do |format|
      if @animation_carousel.save
        format.html { redirect_to @animation_carousel, notice: 'AnimationCarousel was successfully created.' }
        format.json { render json: @animation_carousel, status: :created, location: @animation_carousel }
      else
        format.html { render action: "new" }
        format.json { render json: @animation_carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /animation_carousels/1
  # PUT /animation_carousels/1.json
  def update
    @animation_carousel = AnimationCarousel.find(params[:id])

    respond_to do |format|
      if @animation_carousel.update_attributes(params[:animation_carousel].except(:carousel))
        format.html { redirect_to @animation_carousel, notice: 'AnimationCarousel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @animation_carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animation_carousels/1
  # DELETE /animation_carousels/1.json
  def destroy
    @animation_carousel = AnimationCarousel.find(params[:id])
    @animation_carousel.destroy

    respond_to do |format|
      format.html { redirect_to animation_carousels_url }
      format.json { head :no_content }
    end
  end

  #AJAX add carousel
  def add_carousel

    @animation_carousel = AnimationCarousel.find(params[:animation_carousel_id])
    @carousel = @animation_carousel.carousels.create(params[:animation_carousel][:carousel])

    respond_to do |format|
      format.js #add_carousel.js.erb
    end
  end
end

app/controllers/administracion/animations_controller.rb
class Administracion::AnimationsController < ApplicationController
  layout "administracion"
  
  # GET /animations
  # GET /animations.json
  def index
    @animations = Animation.all

    #@animations = []

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @animations }
    end
  end

  # GET /animations/1
  # GET /animations/1.json
  def show
    @animation = Animation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @animation }
    end
  end

  # GET /animations/new
  # GET /animations/new.json
  def new
    @animation = Animation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @animation }
    end
  end

  # GET /animations/1/edit
  def edit
    @animation = Animation.find(params[:id])
  end

  # POST /animations
  # POST /animations.json
  def create
    @animation = Animation.new(params[:animation])

    respond_to do |format|
      if @animation.save
        format.html { redirect_to @animation, notice: 'animation was successfully created.' }
        format.json { render json: @animation, status: :created, location: @animation }
      else
        format.html { render action: "new" }
        format.json { render json: @animation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /animations/1
  # PUT /animations/1.json
  def update
    @animation = Animation.find(params[:id])

    respond_to do |format|
      if @animation.update_attributes(params[:animation])
        format.html { redirect_to @animation, notice: 'animation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @animation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animations/1
  # DELETE /animations/1.json
  def destroy
    @animation = Animation.find(params[:id])
    @animation.destroy

    respond_to do |format|
      format.html { redirect_to animations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/administracion/events_controller.rb
class Administracion::EventsController < ApplicationController
	http_basic_authenticate_with :name => ENV['U'], :password => ENV['P']
  layout "administracion"
	before_filter :set_event, :except => [:new]

	def new
		@event = Event.new
		@tiendas = Tienda.all
	end

	def create
		event = Event.new(event_params)
		if params[:tienda]
	    tiendas_params.each do |tp|
	    	if tp && tp[:activo] == "on"
	    		tienda_id = tp[:tienda_id]
	    		link = tp[:link]
	    		date = tp[:date].inspect
		    	she = StoreHasEvent.new(:tienda_id=> tienda_id, :link => link, :dates => date, :event_id => event.id)
		    	if she.save
		    		event.store_has_events << she
		    	end
		    end
	    end
	  end
    if event.save
    	redirect_to admin_events_path
    end
	end

	def edit
		@tiendas = Tienda.all
	end

  def update
    event = Event.find(params[:id])
    event.update_attributes(event_params)
    redirect_to admin_events_path
  end

  def destroy
  	event = Event.find(params[:id])
  	event.destroy
  	redirect_to admin_events_path
  end

	private
	  def set_event
	  	@event = Event.find(params[:id]) rescue nil
	  end

	  def event_params
	  	params[:event]
	  end

	  def tiendas_params
	  	params[:tienda]
	  end
end

app/controllers/administracion/store_events_controller.rb
class Administracion::StoreEventsController < ApplicationController
	http_basic_authenticate_with :name => ENV['U'], :password => ENV['P']
	before_filter :set_store_event, :only => [:destroy, :edit, :update]
  layout "administracion"

	def new
		@store_event = StoreEvent.new
	end

	def show
		redirect_to admin_store_events_path
	end

	def create
		se = StoreEvent.new(params_store_event)
		if se.save!
			redirect_to admin_store_events_path
		end
	end

	def update
		@store_event.update_attributes(params_store_event)
		redirect_to admin_store_events_path
	end

	def edit
	end

	def destroy
		if @store_event.destroy
			redirect_to admin_store_events_path
		end
	end


	def params_store_event
		params[:store_event]
	end

	def set_store_event
		@store_event = StoreEvent.find(params[:id])
	end
end

app/helpers/administracion/animations_helper.rb
module Administracion::AnimationsHelper
end

app/helpers/administracion/events_helper.rb
module Administracion::EventsHelper
end

app/helpers/administracion/photogram_helper.rb
module Administracion::PhotogramHelper
end

app/helpers/administracion_helper.rb
module AdministracionHelper
end

app/views/administracion/descontinuados.html.haml
.bs-docs-section.col-12.col-md-12.col-lg-12{:role => "main"}
  .page-header
    %h2#btn-groups
      %i.glyphicon.glyphicon.glyphicon-file
      Descontinuar productos
  .contengoTabla.row-fluid
    = form_tag admin_update_descontinuados_path do
      .col-lg-12.text-center
        .form-group
          %small Selecciona el archivo con el que deseas descontinuar los productos
        .form-group
          = select_tag(:file_id, options_from_collection_for_select(Upload.all, :id, :name), {class: "form-control"})
        .form-group
          = submit_tag 'Descontinuar productos', {class: "btn btn-block btn-info btn-file"}

app/views/administracion/events.html.haml
#main{:vista=>"events"}
	.bs-docs-section.col-12.col-md-12.col-lg-12{:role => "main"}
		.page-header
			%h2#btn-groups
				%i.glyphicon.glyphicon.glyphicon-asterisk
				events
				= link_to "New event", new_admin_event_path, :class=> "btn btn-def pull-right"
		.contengoTabla.row-fluid
			%table.table.table-bordered.table-striped.table-hover
				%thead 
					%tr
						%th.text-center Photo
						%th.text-center Title
						%th.text-center Description
						%th.ver
							%i.glyphicon.glyphicon-eye-open
						%th.editar
							%i.glyphicon.glyphicon-pencil
						%th.eliminar
							%i.glyphicon.glyphicon-remove
				%tbody 
				- for event in @events
					%tr
						%td.text-center= image_tag event.photo, {:class=>"banner"} if event.photo
						%td.text-center= event.title
						%td.text-center= event.description
						%td.text-center
							= link_to "/administracion/events/#{event.id}/" do
								%i.glyphicon.glyphicon-eye-open
						%td.text-center
							= link_to "/administracion/events/#{event.id}/edit" do
								%i.glyphicon.glyphicon-pencil
						%td.text-center
							= link_to admin_event_path(event), {:confirm => 'Are you sure?', :method => :delete} do
								.glyphicon.glyphicon-remove

app/views/administracion/files.html.haml
.bs-docs-section.col-12.col-md-12.col-lg-12{:role => "main"}
  .page-header
    = form_tag admin_upload_file_path, multipart: true do
      .col-lg-8
        %h2
          %i.glyphicon.glyphicon.glyphicon-file
          Files
        .clearfix
      .col-lg-3
        .form-group
          .row
            %label.btn.btn-block.btn-default.btn-file{:for => "file"}
              = file_field_tag :file, {class: "form", onchange: "$('#upload-file-info').html($(this).val());"}
              Browse
            %span#upload-file-info.label.label-info
        .clearfix
      .col-lg-1
        .form-group
          .row.text-right
            = submit_tag 'Upload file', {class: "btn btn-info btn-file"}
        .clearfix
      .clearfix
  .contengoTabla.row-fluid      
    .col-lg-12
      %table.table.table-bordered.table-striped.table-hover
        %thead 
          %tr
            %th.text-center UID
            %th.text-center Name
            %th.text-center Upload Date
            %th.text-center URL
        %tbody 
        - for upload in @uploads
          %tr
            %td.text-center= upload.id
            %td.text-center= upload.name
            %td.text-center= upload.created_at.to_s
            %td.text-center= link_to("descargar", upload.url)
:css
  .btn-file {
      position: relative;
  }
  .btn-file input[type=file] {
      position: absolute;
      top: 0;
      right: 0;
      min-width: 100%;
      min-height: 100%;
      font-size: 100px;
      text-align: right;
      filter: alpha(opacity=0);
      opacity: 0;
      outline: none;
      background: white;
      cursor: inherit;
      display: block;
  }

app/views/administracion/index.html.haml
index.html.haml

app/views/administracion/landings.html.haml
#main{:vista=>"landings"}
	.bs-docs-section.col-12.col-md-12.col-lg-12{:role => "main"}
		.page-header
			%h2#btn-groups
				%i.glyphicon.glyphicon.glyphicon-asterisk
				Brand Landings
				= link_to "New Brand Landing", new_admin_landing_path, :class=> "btn btn-default pull-right"
		.contengoTabla.row-fluid
			%table.table.table-bordered.table-striped.table-hover
				%thead 
					%tr
						%th.text-center Photo
						%th.text-center Link
						%th.text-center Marca
						%th.ver
							%i.glyphicon.glyphicon-eye-open
						%th.editar
							%i.glyphicon.glyphicon-pencil
						%th.eliminar
							%i.glyphicon.glyphicon-remove
				%tbody 
				- for landing in @landings
					%tr
						%td.text-center= image_tag landing.banner, {:class=>"banner"}
						%td.text-center= link_to truncate(landing.link.gsub("http://www.sephora.com.mx", ""), :length => 50), landing.link
						%td.text-center= landing.marca.marca
						%td.text-center= link_to raw("<i class='glyphicon glyphicon-eye-open'></i>"), landing
						%td.text-center= link_to raw("<i class='glyphicon glyphicon-pencil'></i>"), edit_admin_landing_path(landing)
						%td.text-center= link_to raw("<i class='glyphicon glyphicon-remove'></i>"), landing, :confirm => 'Are you sure?', :method => :delete

app/views/administracion/photogram.html.haml
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Object
      %th Object id
      %th Aspect
      %th Callback URL
      %th Type
      %th.text-center
        %i.glyphicon.glyphicon-remove
  %tbody
    - @subscriptions.each do |s|
      %tr
        %td=s.id
        %td=s.object
        %td=s.object_id
        %td=s.aspect
        %td=s.callback_url
        %td=s.type
        %td.text-center= link_to raw("<i class='glyphicon glyphicon-remove'></i>"), admin_photogram_path(s.id), :confirm => 'Are you sure?', :method => :delete

app/views/administracion/prices.html.haml
.bs-docs-section.col-12.col-md-12.col-lg-12{:role => "main"}
  .page-header
    %h2#btn-groups
      %i.glyphicon.glyphicon.glyphicon-file
      Prices
  .contengoTabla.row-fluid
    = form_tag admin_update_prices_path do
      .col-lg-12.text-center
        .form-group
          %small Selecciona el archivo con el que deseas actualizar los precios
        .form-group
          = select_tag(:file_id, options_from_collection_for_select(Upload.all, :id, :name), {class: "form-control"})
        .form-group
          = submit_tag 'Actualizar precios', {class: "btn btn-block btn-info btn-file"}

app/views/administracion/store_events.html.haml
#main{:vista=>"store_events"}
	.bs-docs-section.col-12.col-md-12.col-lg-12{:role => "main"}
		.page-header
			%h2#btn-groups
				%i.glyphicon.glyphicon.glyphicon-asterisk
				Store Events
				= link_to "New event", new_admin_store_event_path, :class=> "btn btn-default pull-right"
		.contengoTabla.row-fluid
			%table.table.table-bordered.table-striped.table-hover
				%thead 
					%tr
						%th.text-center Event photo
						%th.text-center Event title
						%th.text-center Store
						%th.text-center Dates
						%th.text-center Register Link
						%th.ver
							%i.glyphicon.glyphicon-eye-open
						%th.editar
							%i.glyphicon.glyphicon-pencil
						%th.eliminar
							%i.glyphicon.glyphicon-remove
				%tbody 
				- for store_event in @store_events
					- event = Event.find(store_event.event_id)
					- store = Tienda.find(store_event.tienda_id)
					%tr
						%td.text-center= image_tag event.photo, {:class=>"media-object"} if event.photo
						%td.text-center= event.title
						%td.text-center= store.nombre
						%td.text-center= store_event.dates
						%td.text-center= link_to truncate(store_event.link, length: 50), store_event.link
						%td.text-center
							= link_to "/administracion/store_events/#{store_event.id}/" do
								%i.glyphicon.glyphicon-eye-open
						%td.text-center
							= link_to "/administracion/store_events/#{store_event.id}/edit" do
								%i.glyphicon.glyphicon-pencil
						%td.text-center= link_to raw("<i class='glyphicon glyphicon-remove'></i>"), "/administracion/store_events/#{store_event.id}/", :confirm => 'Are you sure?', :method => :delete

app/views/administracion/update_descontinuados.html.haml
- if flash[:notice].present?
  .alert.alert-warning
    %p=flash[:notice]
.bs-docs-section.col-12.col-md-12.col-lg-12{:role => "main"}
  .page-header
    %h2#btn-groups
      %i.glyphicon.glyphicon.glyphicon-file
      Productos Descontinuados
  .contengoTabla.row-fluid
    %table.table.table-bordered.table-striped.table-hover
      %thead 
        %tr
          %th Antes
          %th Despues
      -if @descontinuados.present?
        %tbody
          %tr
            %td=@descontinuados[:before]
            %td=@descontinuados[:after]

app/views/administracion/update_prices.html.haml
- if flash[:notice].present?
  .alert.alert-warning
    %p=flash[:notice]
.bs-docs-section.col-12.col-md-12.col-lg-12{:role => "main"}
  .page-header
    %h2#btn-groups
      %i.glyphicon.glyphicon.glyphicon-file
      Prices
  .contengoTabla.row-fluid
    %table.table.table-bordered.table-striped.table-hover
      %thead 
        %tr
          %th UPC
          %th Precio Anterior
          %th Precio Nuevo
      %tbody
        -@prices.each do |price|
          %tr
            %td=price[:upc]
            %td=price[:precio]
            %td=price[:nuevo_precio]